# Generated by Django 4.2.3 on 2026-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='extracted_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
