# Generated by Django 5.2.12 on 2026-04-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0003_alter_bill_bill_date_alter_bill_hospital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='extracted_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='total_overcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='charged_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
