# Generated by Django 5.2.12 on 2026-04-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0004_alter_analysisreport_extracted_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='account_balance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_name_on_bill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
