# Generated by Django 4.2.3 on 2026-04-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0005_bill_account_balance_bill_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='billing_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
