# Generated by Django 4.2.3 on 2026-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0006_bill_admission_number_bill_billing_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
