# Generated by Django 4.2.11 on 2026-04-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0007_bill_admission_date_bill_discharge_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='account_balance',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='billing_hours',
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
