# Generated by Django 5.2.15 on 2026-06-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email_draft',
            field=models.TextField(blank=True, null=True),
        ),
    ]
